---
antora:
  name: modules
  dir: www
  modules:
    - name: "module-01"
      label: "System setup"
      solveButton: false
    - name: "module-02"
      label: "Building the first bootc container"
      solveButton: false
    - name: "module-03"
      label: "Deploying a virtual machine with bootc image"
      solveButton: false
    - name: "module-04"
      label: "Changing bootc hosts"
      solveButton: false
    - name: "module-05"
      label: "Rolling back a bootc host"
      solveButton: false
    - name: "module-06"
      label: "Applying RHEL updates to the bootc base images"
      solveButton: false
    - name: "module-07"
      label: "Repurposing a bootc host"
      solveButton: false
    - name: "module-08"
      label: "Building an unattended install disk ISO"
      solveButton: false
    - name: "module-09"
      label: "Embedding credentials in an image"
      solveButton: false
    - name: "module-10"
      label: "Dev mod troubleshoot"
      solveButton: false
    - name: "module-11"
      label: "Dev mod rebase"
      solveButton: false
    - name: "module-12"
      label: "Dev mod idiomatic"
      solveButton: false
    - name: "module-13"
      label: "Dev mod movin day"
      solveButton: false
    - name: "module-drivers"
      label: "Platform targets"
      solveButton: false
    - name: "module-14"
      label: "Scratch builds"
      solveButton: false
    - name: "module-15"
      label: "Rechunk"
      solveButton: false
    - name: "module-16"
      label: "Reproducibility"
      solveButton: false

tabs:
  - name: "Build host"
    url: /wetty/ssh/root
  - name: "VM SSH session"
    url: /wetty_bootc_vm/ssh/root
  - name: "ISO SSH session"
    url: /wetty_iso_vm/ssh/root
  - name: ">_ Image mode host"
    url: /wetty_imrhel/ssh/root
    modules:
      - module-10
      - module-11
      - module-12
      - module-13
      - module-14
